### ISSUE TITLE
enhance help text for stage and test releases

### ISSUE THREAD

**Issue by pnemade** [juhp/dl-fedora#1]
I like this tool to use whenever I need any Fedora iso to download. But I get confused sometimes what `RELEASE` to use for release candidate images or Beta released images.

Can `dl-fedora` command help output text be enhanced to give users information that `stage` means release candidate images and `test` mean beta releases?

**Comment by juhp** [comment]
Thanks for the suggestion, I think that can be done easily yes.

**Comment by juhp** [comment]
It took a long time but this should be in the coming 0.7.6 release
